/**
 * Shared strict oxlint preset: every Ultracite preset this stack uses, the
 * JS-plugin rules (react-doctor, sonarjs, @shadcn/lint, anti-slop), and the
 * project-local rules in `oxlint-plugin-local.ts` and the test-quality rules in
 * `oxlint-plugin-test-quality.ts`. The root `oxlint.config.ts`
 * re-exports it (a nested `oxlint.config.ts` would be picked up as a
 * per-directory config, hence the `.preset.ts` name).
 *
 * Zero warnings are allowed (`ultracite check --max-warnings 0`). Turning a
 * rule off needs a one-line justification next to it.
 */
import { fileURLToPath } from "node:url";

import { defineConfig } from "oxlint";
import antiSlop from "ultracite/oxlint/anti-slop";
import astro from "ultracite/oxlint/astro";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import react from "ultracite/oxlint/react";
import shadcn from "ultracite/oxlint/shadcn";
import vitest from "ultracite/oxlint/vitest";

const jsPlugins = selectJsPlugins(["react-doctor", "sonarjs"]);

export default defineConfig({
  extends: [core, react, astro, vitest, shadcn, antiSlop, jsPlugins],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // shadcn/ui primitives are vendored from the registry; re-sync with `shadcn add`, don't hand-edit.
    "**/src/components/ui/**",
    // Generated by EmDash from the live schema on every dev-server start.
    "**/emdash-env.d.ts",
    // Upstream sources cloned for agents by scripts/sync-references.ts (gitignored).
    ".repos/**",
    // Throwaway experiments kept for reference; not part of the template.
    "spikes/**",
  ],
  // Oxlint does not merge `jsPlugins` from extended configs; declare every preset's plugins here.
  jsPlugins: [
    ...jsPlugins.jsPlugins,
    ...(shadcn.jsPlugins ?? []),
    ...(antiSlop.jsPlugins ?? []),
    {
      name: "local",
      specifier: fileURLToPath(
        new URL("oxlint-plugin-local.ts", import.meta.url)
      ),
    },
    {
      name: "test-quality",
      specifier: fileURLToPath(
        new URL("oxlint-plugin-test-quality.ts", import.meta.url)
      ),
    },
  ],
  options: { typeAware: true },
  overrides: [
    {
      // Developer CLIs (never deployed): they shell out to git/bun/gh from the developer's PATH,
      // and browser automation, polling, and gate runs are sequential by design.
      files: [
        "scripts/**",
        "stacks/**/*.ts",
        "packages/control-app/**",
        "packages/proof/src/cli.ts",
        "packages/cloudflare-kit/src/infra/secrets.ts",
      ],
      rules: {
        "eslint/no-await-in-loop": "off",
        "react-doctor/async-await-in-loop": "off",
        "sonarjs/no-os-command-from-path": "off",
      },
    },
    {
      // A dev page can answer 200 and then never finish streaming; a bare fetch waits on it
      // for Bun's 5-minute default. control-app requests go through `request()` instead.
      files: ["packages/control-app/src/**"],
      rules: {
        "eslint/no-restricted-globals": [
          "error",
          {
            message:
              "Use request() from ./http.ts: it gives every request (body included) a timeout.",
            name: "fetch",
          },
        ],
      },
    },
    {
      files: ["**/oxlint-plugin-*.ts"],
      rules: {
        // Rule visitors are keyed by ESTree node type names (`JSXAttribute`, `Literal`).
        "sonarjs/function-name": "off",
      },
    },
    {
      files: ["**/*.test.ts", "**/*.test.tsx"],
      plugins: ["vitest"],
      rules: {
        // Rule tests embed the forbidden dashes as fixtures.
        "local/no-long-dashes": "off",
        // Expected values are literals, not computed with the module under test.
        "test-quality/no-self-referential-expected": "error",
        // At least one assertion pins a produced value, not only absence, presence, or type.
        "test-quality/no-weak-only-assertions": "error",
        // The test runs code instead of only reading constants or its own fixtures.
        "test-quality/require-subject-call": "error",
        // @effect/vitest's `it.effect` is a test block.
        "vitest/no-standalone-expect": [
          "error",
          {
            additionalTestBlockFunctions: ["it.effect", "it.live", "it.scoped"],
          },
        ],
      },
    },
    {
      files: ["**/oxlint-plugin-*.test.ts"],
      rules: {
        // RuleTester registers its cases through RuleTester.describe/it, which sonarjs cannot see.
        "sonarjs/no-empty-test-file": "off",
        // RuleTester's describe/it hooks are typed `void`; Vitest's return a suite/test handle.
        "typescript/strict-void-return": "off",
      },
    },
  ],
  rules: {
    "local/no-long-dashes": "error",
    "local/no-transition-colors": "error",
    "local/prefer-shared-controls": "error",
    // Effect modules co-locate a service class with the tagged error classes it fails with.
    "max-classes-per-file": "off",
    // TypeScript rejects real redeclarations; this flags the Effect idiom of a schema and its type sharing a name.
    "no-redeclare": "off",
    // Effect error handlers (`Effect.catchTag("X", (error) => ...)`) are not Node-style callbacks.
    "promise/prefer-await-to-callbacks": "off",
    // `import * as Cloudflare from "alchemy/Cloudflare"` is the documented Alchemy/Effect idiom: the namespace is the API.
    "sonarjs/no-wildcard-import": "off",
    // Effect's `Schema.TaggedError<T>()(...)` factory ends in "Error" and must not take `new`;
    // this rule's autofix inserts `new` and breaks every Effect error class.
    "unicorn/throw-new-error": "off",
  },
  // Oxlint does not merge `settings` from extended configs; react-doctor needs these on the root.
  settings: jsPluginSettings,
});
